language: python
sudo: required
dist: trusty
python:
    - "2.7"
before_install:
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install -y python-clang-3.7 libclang1-3.7
    - ln -s /usr/lib/python2.7/dist-packages/clang
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/llvm-3.7/lib/
    - pip install -r requirements.txt
script:
    - coverage run setup.py test
    - coverage report --show-missing
after_success:
    - coveralls
