sudo: false
language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - LLVM_HOME=/usr/lib/llvm-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages: 
      - clang-3.8
      - libclang-3.8-dev

install:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LLVM_HOME/lib
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then ln -s /usr/lib/python2.7/dist-packages/clang; fi
  - pip install -r requirements.txt
  - python setup.py install

script:
  - python setup.py nosetests 
  - coverage report --show-missing

after_success:
  - coveralls

